
import streamlit as st
st.set_page_config(page_title="QuLab - Explainable Credit Scoring", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab: Explainable Credit Scoring")
st.divider()

st.markdown("""
In this lab, you step into the shoes of a **Quantitative Analyst** at a leading financial institution.
Your institution is facing increased regulatory scrutiny regarding its automated credit decision-making process.
Specifically, there's a demand for greater transparency, especially concerning rejected loan applications.

Your mission is to leverage **Explainable AI (XAI)** techniques to justify loan application outcomes.
Navigate through each page to complete the workflow and test your knowledge with the final quiz!
""")

page = st.sidebar.selectbox(
    label="Navigation", 
    options=[
        "Data Inspection", 
        "Model Training", 
        "Case Identification", 
        "LIME Explanation & Visualization", 
        "SHAP Explanation & Visualization",
        "Explanation Synthesis",
        "Global Insights",
        "Quiz"
    ]
)

if page == "Data Inspection":
    from application_pages.page_2_data_inspection import main
    main()
elif page == "Model Training":
    from application_pages.page_3_model_training import main
    main()
elif page == "Case Identification":
    from application_pages.page_4_case_identification import main
    main()
elif page == "LIME Explanation & Visualization":
    from application_pages.page_5_lime_explanation import main
    main()
elif page == "SHAP Explanation & Visualization":
    from application_pages.page_7_shap_explanation import main
    main()
elif page == "Explanation Synthesis":
    from application_pages.page_9_explanation_synthesis import main
    main()
elif page == "Global Insights":
    from application_pages.page_10_global_insights import main
    main()
elif page == "Quiz":
    from application_pages.page_11_quiz import main
    main()


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@qusandbox.com](mailto:info@qusandbox.com)
''')
